language: c++
before_install:
- sudo apt-get update -qq
- sudo apt-get clean
- sudo apt-get install libglm-dev libpng-dev ftjam
- |
  travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.8.tar.gz | tar xz
  cd SDL2-2.0.8
  ./configure
  make
  sudo make install
script:
- jam
